/* Auto-generated by genmsg_cpp for file /projects/ros/surfer-main/lab3/hovercraft/msg/BatteryVoltage.msg */
#ifndef HOVERCRAFT_MESSAGE_BATTERYVOLTAGE_H
#define HOVERCRAFT_MESSAGE_BATTERYVOLTAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace hovercraft
{
template <class ContainerAllocator>
struct BatteryVoltage_ {
  typedef BatteryVoltage_<ContainerAllocator> Type;

  BatteryVoltage_()
  : header()
  , voltage(0.0)
  {
  }

  BatteryVoltage_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , voltage(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _voltage_type;
  double voltage;


  typedef boost::shared_ptr< ::hovercraft::BatteryVoltage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hovercraft::BatteryVoltage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BatteryVoltage
typedef  ::hovercraft::BatteryVoltage_<std::allocator<void> > BatteryVoltage;

typedef boost::shared_ptr< ::hovercraft::BatteryVoltage> BatteryVoltagePtr;
typedef boost::shared_ptr< ::hovercraft::BatteryVoltage const> BatteryVoltageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hovercraft::BatteryVoltage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hovercraft::BatteryVoltage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hovercraft

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hovercraft::BatteryVoltage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hovercraft::BatteryVoltage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hovercraft::BatteryVoltage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eaf4d0e55ee7ea889fa473746e54d896";
  }

  static const char* value(const  ::hovercraft::BatteryVoltage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeaf4d0e55ee7ea88ULL;
  static const uint64_t static_value2 = 0x9fa473746e54d896ULL;
};

template<class ContainerAllocator>
struct DataType< ::hovercraft::BatteryVoltage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hovercraft/BatteryVoltage";
  }

  static const char* value(const  ::hovercraft::BatteryVoltage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hovercraft::BatteryVoltage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# In volts\n\
float64 voltage\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hovercraft::BatteryVoltage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hovercraft::BatteryVoltage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hovercraft::BatteryVoltage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hovercraft::BatteryVoltage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.voltage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BatteryVoltage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hovercraft::BatteryVoltage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hovercraft::BatteryVoltage_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HOVERCRAFT_MESSAGE_BATTERYVOLTAGE_H

