/* Auto-generated by genmsg_cpp for file /home/courtney/groovy_ws/projects/ros/surfer-main/lab3/hovercraft/msg/Gyro.msg */
#ifndef HOVERCRAFT_MESSAGE_GYRO_H
#define HOVERCRAFT_MESSAGE_GYRO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace hovercraft
{
template <class ContainerAllocator>
struct Gyro_ {
  typedef Gyro_<ContainerAllocator> Type;

  Gyro_()
  : header()
  , angle(0.0)
  , rate(0.0)
  {
  }

  Gyro_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , angle(0.0)
  , rate(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _angle_type;
  double angle;

  typedef double _rate_type;
  double rate;


  typedef boost::shared_ptr< ::hovercraft::Gyro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hovercraft::Gyro_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Gyro
typedef  ::hovercraft::Gyro_<std::allocator<void> > Gyro;

typedef boost::shared_ptr< ::hovercraft::Gyro> GyroPtr;
typedef boost::shared_ptr< ::hovercraft::Gyro const> GyroConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hovercraft::Gyro_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hovercraft::Gyro_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hovercraft

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hovercraft::Gyro_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hovercraft::Gyro_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hovercraft::Gyro_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ec693c46cb4f5c6bdb741fcf98f2175e";
  }

  static const char* value(const  ::hovercraft::Gyro_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xec693c46cb4f5c6bULL;
  static const uint64_t static_value2 = 0xdb741fcf98f2175eULL;
};

template<class ContainerAllocator>
struct DataType< ::hovercraft::Gyro_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hovercraft/Gyro";
  }

  static const char* value(const  ::hovercraft::Gyro_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hovercraft::Gyro_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# Gyro reported angle in degrees\n\
float64 angle\n\
# Gyro reported rate in degrees per second\n\
float64 rate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hovercraft::Gyro_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hovercraft::Gyro_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hovercraft::Gyro_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hovercraft::Gyro_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.angle);
    stream.next(m.rate);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Gyro_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hovercraft::Gyro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hovercraft::Gyro_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "rate: ";
    Printer<double>::stream(s, indent + "  ", v.rate);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HOVERCRAFT_MESSAGE_GYRO_H

