/* Auto-generated by genmsg_cpp for file /home/refnode/projects/Ref/msg/controls.msg */
#ifndef REF_MESSAGE_CONTROLS_H
#define REF_MESSAGE_CONTROLS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace Ref
{
template <class ContainerAllocator>
struct controls_ {
  typedef controls_<ContainerAllocator> Type;

  controls_()
  : header()
  , liftchanges()
  {
  }

  controls_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , liftchanges(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _liftchanges_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  liftchanges;


  typedef boost::shared_ptr< ::Ref::controls_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Ref::controls_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct controls
typedef  ::Ref::controls_<std::allocator<void> > controls;

typedef boost::shared_ptr< ::Ref::controls> controlsPtr;
typedef boost::shared_ptr< ::Ref::controls const> controlsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Ref::controls_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Ref::controls_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Ref

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Ref::controls_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Ref::controls_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Ref::controls_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7847fb6cbdfd71e4ceb02775ea5a57bf";
  }

  static const char* value(const  ::Ref::controls_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7847fb6cbdfd71e4ULL;
  static const uint64_t static_value2 = 0xceb02775ea5a57bfULL;
};

template<class ContainerAllocator>
struct DataType< ::Ref::controls_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Ref/controls";
  }

  static const char* value(const  ::Ref::controls_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Ref::controls_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
bool[] liftchanges\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::Ref::controls_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::Ref::controls_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::Ref::controls_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Ref::controls_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.liftchanges);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct controls_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Ref::controls_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Ref::controls_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "liftchanges[]" << std::endl;
    for (size_t i = 0; i < v.liftchanges.size(); ++i)
    {
      s << indent << "  liftchanges[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.liftchanges[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // REF_MESSAGE_CONTROLS_H

