/* Auto-generated by genmsg_cpp for file /home/refnode/projects/Ref/msg/HoverBot.msg */
#ifndef REF_MESSAGE_HOVERBOT_H
#define REF_MESSAGE_HOVERBOT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace Ref
{
template <class ContainerAllocator>
struct HoverBot_ {
  typedef HoverBot_<ContainerAllocator> Type;

  HoverBot_()
  : header()
  , botID(0)
  , checkpoint()
  , powerup(0)
  , canRun(false)
  {
  }

  HoverBot_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , botID(0)
  , checkpoint(_alloc)
  , powerup(0)
  , canRun(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _botID_type;
  int8_t botID;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _checkpoint_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  checkpoint;

  typedef int8_t _powerup_type;
  int8_t powerup;

  typedef uint8_t _canRun_type;
  uint8_t canRun;


  typedef boost::shared_ptr< ::Ref::HoverBot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Ref::HoverBot_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HoverBot
typedef  ::Ref::HoverBot_<std::allocator<void> > HoverBot;

typedef boost::shared_ptr< ::Ref::HoverBot> HoverBotPtr;
typedef boost::shared_ptr< ::Ref::HoverBot const> HoverBotConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Ref::HoverBot_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Ref::HoverBot_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Ref

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Ref::HoverBot_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Ref::HoverBot_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Ref::HoverBot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f8385bf7604a2ee8d25d1f50a55982b3";
  }

  static const char* value(const  ::Ref::HoverBot_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf8385bf7604a2ee8ULL;
  static const uint64_t static_value2 = 0xd25d1f50a55982b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::Ref::HoverBot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Ref/HoverBot";
  }

  static const char* value(const  ::Ref::HoverBot_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Ref::HoverBot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
int8 botID\n\
\n\
int32[] checkpoint\n\
\n\
int8 powerup\n\
\n\
bool canRun\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::Ref::HoverBot_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::Ref::HoverBot_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::Ref::HoverBot_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Ref::HoverBot_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.botID);
    stream.next(m.checkpoint);
    stream.next(m.powerup);
    stream.next(m.canRun);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HoverBot_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Ref::HoverBot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Ref::HoverBot_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "botID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.botID);
    s << indent << "checkpoint[]" << std::endl;
    for (size_t i = 0; i < v.checkpoint.size(); ++i)
    {
      s << indent << "  checkpoint[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.checkpoint[i]);
    }
    s << indent << "powerup: ";
    Printer<int8_t>::stream(s, indent + "  ", v.powerup);
    s << indent << "canRun: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canRun);
  }
};


} // namespace message_operations
} // namespace ros

#endif // REF_MESSAGE_HOVERBOT_H

