/* Auto-generated by genmsg_cpp for file /projects/ros/surfer-main/lab3/Ref/msg/image.msg */
#ifndef REF_MESSAGE_IMAGE_H
#define REF_MESSAGE_IMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "Ref/Position.h"

namespace Ref
{
template <class ContainerAllocator>
struct image_ {
  typedef image_<ContainerAllocator> Type;

  image_()
  : header()
  , bots()
  {
  }

  image_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , bots(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::Ref::Position_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::Ref::Position_<ContainerAllocator> >::other >  _bots_type;
  std::vector< ::Ref::Position_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::Ref::Position_<ContainerAllocator> >::other >  bots;


  typedef boost::shared_ptr< ::Ref::image_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Ref::image_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct image
typedef  ::Ref::image_<std::allocator<void> > image;

typedef boost::shared_ptr< ::Ref::image> imagePtr;
typedef boost::shared_ptr< ::Ref::image const> imageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Ref::image_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Ref::image_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Ref

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Ref::image_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Ref::image_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Ref::image_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f5f5ba95d6a5e2a82d553cdc6692532a";
  }

  static const char* value(const  ::Ref::image_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf5f5ba95d6a5e2a8ULL;
  static const uint64_t static_value2 = 0x2d553cdc6692532aULL;
};

template<class ContainerAllocator>
struct DataType< ::Ref::image_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Ref/image";
  }

  static const char* value(const  ::Ref::image_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Ref::image_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
Position[] bots\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: Ref/Position\n\
float32 x\n\
float32 y\n\
float32 rot\n\
\n\
";
  }

  static const char* value(const  ::Ref::image_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::Ref::image_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::Ref::image_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Ref::image_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.bots);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct image_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Ref::image_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Ref::image_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bots[]" << std::endl;
    for (size_t i = 0; i < v.bots.size(); ++i)
    {
      s << indent << "  bots[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::Ref::Position_<ContainerAllocator> >::stream(s, indent + "    ", v.bots[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // REF_MESSAGE_IMAGE_H

