/* Auto-generated by genmsg_cpp for file /home/courtney/groovy_ws/projects/ros/surfer-main/lab2/hovercraft/msg/LED.msg */
#ifndef HOVERCRAFT_MESSAGE_LED_H
#define HOVERCRAFT_MESSAGE_LED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace hovercraft
{
template <class ContainerAllocator>
struct LED_ {
  typedef LED_<ContainerAllocator> Type;

  LED_()
  : header()
  , led33_red(0)
  , led33_green(0)
  {
  }

  LED_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , led33_red(0)
  , led33_green(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _led33_red_type;
  int8_t led33_red;

  typedef int8_t _led33_green_type;
  int8_t led33_green;


  typedef boost::shared_ptr< ::hovercraft::LED_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hovercraft::LED_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LED
typedef  ::hovercraft::LED_<std::allocator<void> > LED;

typedef boost::shared_ptr< ::hovercraft::LED> LEDPtr;
typedef boost::shared_ptr< ::hovercraft::LED const> LEDConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hovercraft::LED_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hovercraft::LED_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hovercraft

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hovercraft::LED_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hovercraft::LED_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hovercraft::LED_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3179455e6b99aaaed74f73183b013321";
  }

  static const char* value(const  ::hovercraft::LED_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3179455e6b99aaaeULL;
  static const uint64_t static_value2 = 0xd74f73183b013321ULL;
};

template<class ContainerAllocator>
struct DataType< ::hovercraft::LED_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hovercraft/LED";
  }

  static const char* value(const  ::hovercraft::LED_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hovercraft::LED_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# 1 to turn on the specified LED, 0 to turn it off, \n\
# 2 to toggle, -1 to keep current value.\n\
int8 led33_red\n\
int8 led33_green\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hovercraft::LED_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hovercraft::LED_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hovercraft::LED_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hovercraft::LED_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.led33_red);
    stream.next(m.led33_green);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LED_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hovercraft::LED_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hovercraft::LED_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "led33_red: ";
    Printer<int8_t>::stream(s, indent + "  ", v.led33_red);
    s << indent << "led33_green: ";
    Printer<int8_t>::stream(s, indent + "  ", v.led33_green);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HOVERCRAFT_MESSAGE_LED_H

