/* Auto-generated by genmsg_cpp for file /projects/ros/surfer-main/lab3/hoverboard/msg/GPIORaw.msg */
#ifndef HOVERBOARD_MESSAGE_GPIORAW_H
#define HOVERBOARD_MESSAGE_GPIORAW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace hoverboard
{
template <class ContainerAllocator>
struct GPIORaw_ {
  typedef GPIORaw_<ContainerAllocator> Type;

  GPIORaw_()
  : header()
  , gpio33_0(0)
  , gpio33_1(0)
  , gpio33_2(0)
  , gpio33_3(0)
  , gpio33_4(0)
  , gpio33_5(0)
  , gpio5_0(0)
  , gpio5_1(0)
  , gpio5_2(0)
  , gpio5_3(0)
  , gpio5_4(0)
  , gpio5_5(0)
  {
  }

  GPIORaw_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , gpio33_0(0)
  , gpio33_1(0)
  , gpio33_2(0)
  , gpio33_3(0)
  , gpio33_4(0)
  , gpio33_5(0)
  , gpio5_0(0)
  , gpio5_1(0)
  , gpio5_2(0)
  , gpio5_3(0)
  , gpio5_4(0)
  , gpio5_5(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _gpio33_0_type;
  int8_t gpio33_0;

  typedef int8_t _gpio33_1_type;
  int8_t gpio33_1;

  typedef int8_t _gpio33_2_type;
  int8_t gpio33_2;

  typedef int8_t _gpio33_3_type;
  int8_t gpio33_3;

  typedef int8_t _gpio33_4_type;
  int8_t gpio33_4;

  typedef int8_t _gpio33_5_type;
  int8_t gpio33_5;

  typedef int8_t _gpio5_0_type;
  int8_t gpio5_0;

  typedef int8_t _gpio5_1_type;
  int8_t gpio5_1;

  typedef int8_t _gpio5_2_type;
  int8_t gpio5_2;

  typedef int8_t _gpio5_3_type;
  int8_t gpio5_3;

  typedef int8_t _gpio5_4_type;
  int8_t gpio5_4;

  typedef int8_t _gpio5_5_type;
  int8_t gpio5_5;


  typedef boost::shared_ptr< ::hoverboard::GPIORaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoverboard::GPIORaw_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GPIORaw
typedef  ::hoverboard::GPIORaw_<std::allocator<void> > GPIORaw;

typedef boost::shared_ptr< ::hoverboard::GPIORaw> GPIORawPtr;
typedef boost::shared_ptr< ::hoverboard::GPIORaw const> GPIORawConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hoverboard::GPIORaw_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hoverboard::GPIORaw_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hoverboard

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hoverboard::GPIORaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hoverboard::GPIORaw_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hoverboard::GPIORaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "69e3b5824711a9cb06bff3f258b81857";
  }

  static const char* value(const  ::hoverboard::GPIORaw_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x69e3b5824711a9cbULL;
  static const uint64_t static_value2 = 0x06bff3f258b81857ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoverboard::GPIORaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hoverboard/GPIORaw";
  }

  static const char* value(const  ::hoverboard::GPIORaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hoverboard::GPIORaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# GPIO values for the 3.3V processor.  -1 indicates that\n\
# It has not been read, 0 if it is at a logic low level and\n\
# 1 for a logic high level\n\
int8 gpio33_0\n\
int8 gpio33_1\n\
int8 gpio33_2\n\
int8 gpio33_3\n\
int8 gpio33_4\n\
int8 gpio33_5\n\
\n\
# GPIO values for the 5.0V processor.  -1 indicates that\n\
# It has not been read, 0 if it is at a logic low level and\n\
# 1 for a logic high level\n\
int8 gpio5_0\n\
int8 gpio5_1\n\
int8 gpio5_2\n\
int8 gpio5_3\n\
int8 gpio5_4\n\
int8 gpio5_5\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hoverboard::GPIORaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hoverboard::GPIORaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hoverboard::GPIORaw_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hoverboard::GPIORaw_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.gpio33_0);
    stream.next(m.gpio33_1);
    stream.next(m.gpio33_2);
    stream.next(m.gpio33_3);
    stream.next(m.gpio33_4);
    stream.next(m.gpio33_5);
    stream.next(m.gpio5_0);
    stream.next(m.gpio5_1);
    stream.next(m.gpio5_2);
    stream.next(m.gpio5_3);
    stream.next(m.gpio5_4);
    stream.next(m.gpio5_5);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GPIORaw_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoverboard::GPIORaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hoverboard::GPIORaw_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gpio33_0: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio33_0);
    s << indent << "gpio33_1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio33_1);
    s << indent << "gpio33_2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio33_2);
    s << indent << "gpio33_3: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio33_3);
    s << indent << "gpio33_4: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio33_4);
    s << indent << "gpio33_5: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio33_5);
    s << indent << "gpio5_0: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio5_0);
    s << indent << "gpio5_1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio5_1);
    s << indent << "gpio5_2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio5_2);
    s << indent << "gpio5_3: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio5_3);
    s << indent << "gpio5_4: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio5_4);
    s << indent << "gpio5_5: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gpio5_5);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HOVERBOARD_MESSAGE_GPIORAW_H

