Header header

#All of the adc values for the 5V processor on the hoverboard.  The
#values are in mV, with -1 indicating this value was not
#received/populated.

int32 adc5_0
int32 adc5_1
int32 adc5_2
int32 adc5_3
int32 adc5_4
int32 adc5_5
int32 adc5_6
int32 adc5_7

#All of the adc values for the 3.3V processor on the hoverboard.  The
#values are in mV, with -1 indicating this value was not
#received/populated.

int32 adc33_0
int32 adc33_1
int32 adc33_2
int32 adc33_3
int32 adc33_4
int32 adc33_5


