/* Auto-generated by genmsg_cpp for file /home/courtney/groovy_ws/projects/ros/surfer-main/lab2/arbitrator/msg/ArbAngle.msg */
#ifndef ARBITRATOR_MESSAGE_ARBANGLE_H
#define ARBITRATOR_MESSAGE_ARBANGLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace arbitrator
{
template <class ContainerAllocator>
struct ArbAngle_ {
  typedef ArbAngle_<ContainerAllocator> Type;

  ArbAngle_()
  : header()
  , angle(0.0)
  , x_axis(0.0)
  , y_axis(0.0)
  {
  }

  ArbAngle_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , angle(0.0)
  , x_axis(0.0)
  , y_axis(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _angle_type;
  double angle;

  typedef float _x_axis_type;
  float x_axis;

  typedef float _y_axis_type;
  float y_axis;


  typedef boost::shared_ptr< ::arbitrator::ArbAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbitrator::ArbAngle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ArbAngle
typedef  ::arbitrator::ArbAngle_<std::allocator<void> > ArbAngle;

typedef boost::shared_ptr< ::arbitrator::ArbAngle> ArbAnglePtr;
typedef boost::shared_ptr< ::arbitrator::ArbAngle const> ArbAngleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arbitrator::ArbAngle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arbitrator::ArbAngle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arbitrator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arbitrator::ArbAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arbitrator::ArbAngle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arbitrator::ArbAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d6d2618c3edfd25dca188f9806ba616a";
  }

  static const char* value(const  ::arbitrator::ArbAngle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd6d2618c3edfd25dULL;
  static const uint64_t static_value2 = 0xca188f9806ba616aULL;
};

template<class ContainerAllocator>
struct DataType< ::arbitrator::ArbAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arbitrator/ArbAngle";
  }

  static const char* value(const  ::arbitrator::ArbAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arbitrator::ArbAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# Target angle\n\
float64 angle\n\
\n\
# Current axis values\n\
float32 x_axis\n\
float32 y_axis\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::arbitrator::ArbAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::arbitrator::ArbAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::arbitrator::ArbAngle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arbitrator::ArbAngle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.angle);
    stream.next(m.x_axis);
    stream.next(m.y_axis);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ArbAngle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbitrator::ArbAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arbitrator::ArbAngle_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "x_axis: ";
    Printer<float>::stream(s, indent + "  ", v.x_axis);
    s << indent << "y_axis: ";
    Printer<float>::stream(s, indent + "  ", v.y_axis);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARBITRATOR_MESSAGE_ARBANGLE_H

