/* Auto-generated by genmsg_cpp for file /home/courtney/groovy_ws/projects/ros/surfer-main/lab2/arbitrator/msg/ArbAngle.msg */
#ifndef ARBITRATOR_MESSAGE_ARBANGLE_H
#define ARBITRATOR_MESSAGE_ARBANGLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arbitrator
{
template <class ContainerAllocator>
struct ArbAngle_ {
  typedef ArbAngle_<ContainerAllocator> Type;

  ArbAngle_()
  : angle(0.0)
  {
  }

  ArbAngle_(const ContainerAllocator& _alloc)
  : angle(0.0)
  {
  }

  typedef double _angle_type;
  double angle;


  typedef boost::shared_ptr< ::arbitrator::ArbAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbitrator::ArbAngle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ArbAngle
typedef  ::arbitrator::ArbAngle_<std::allocator<void> > ArbAngle;

typedef boost::shared_ptr< ::arbitrator::ArbAngle> ArbAnglePtr;
typedef boost::shared_ptr< ::arbitrator::ArbAngle const> ArbAngleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arbitrator::ArbAngle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arbitrator::ArbAngle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arbitrator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arbitrator::ArbAngle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arbitrator::ArbAngle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arbitrator::ArbAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const  ::arbitrator::ArbAngle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::arbitrator::ArbAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arbitrator/ArbAngle";
  }

  static const char* value(const  ::arbitrator::ArbAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arbitrator::ArbAngle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Gyro reported angle in degrees\n\
float64 angle\n\
\n\
";
  }

  static const char* value(const  ::arbitrator::ArbAngle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arbitrator::ArbAngle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arbitrator::ArbAngle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ArbAngle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbitrator::ArbAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arbitrator::ArbAngle_<ContainerAllocator> & v) 
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARBITRATOR_MESSAGE_ARBANGLE_H

